sudo: required

language: bash
services: docker

env:
  - VERSION=6.10  TAG_1=6 TAG_2=6.10.2  TAG_3=boron TAG_4=latest
  - VERSION=4.8   TAG_1=4 TAG_2=4.8.2   TAG_3=argon

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "${VERSION}${VARIANT:+/$VARIANT}"
  - IMAGE_REPOSITORY="${DOCKER_HUB_USERNAME}/node"
  - image="${IMAGE_REPOSITORY}:${VERSION}${VARIANT:+-$VARIANT}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_success:
  - if [ "$TAG_1" != "" ]; then docker tag "${image}" "$IMAGE_REPOSITORY:${TAG_1}" ; fi
  - if [ "$TAG_2" != "" ]; then docker tag "${image}" "$IMAGE_REPOSITORY:${TAG_2}" ; fi
  - if [ "$TAG_3" != "" ]; then docker tag "${image}" "$IMAGE_REPOSITORY:${TAG_3}" ; fi
  - if [ "$TAG_4" != "" ]; then docker tag "${image}" "$IMAGE_REPOSITORY:${TAG_4}" ; fi
  - docker images
  - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
  - docker push ${IMAGE_REPOSITORY}




